export const clients = [
  {
    name: 'joao silva',
    birth: '1999-12-07',
    cpf: '952.402.500-06',
    gender: 'masculino',
    adress: {
      street: 'cascavel',
      number: '2826',
      district: 'boqueirao',
      city: 'curitiba',
      state: 'Parana',
    },
    status: 'ativo',
    editing: false,
  },
  {
    name: 'isadora lincon',
    birth: '1988-12-07',
    cpf: '298.662.470-74',
    gender: 'feminino',
    adress: {
      street: 'Pedro Ivo',
      number: '102',
      district: 'montSerrat',
      city: 'porto alegre',
      state: 'rio grande do sul',
    },
    status: 'ativo',
    editing: false,
  },
  {
    name: 'maria joaquina',
    birth: '1991-12-07',
    cpf: '692.051.090-10',
    gender: 'feminino',
    adress: {
      street: 'Av. Mariland',
      number: '1442',
      district: 'sao joao',
      city: 'porto alegre',
      state: 'rio grande do sul',
    },
    status: 'ativo',
    editing: false,
  },
  {
    name: 'arnaldo suarchineguer',
    birth: '2002-12-07',
    cpf: '676.876.990-17',
    gender: 'masculino',
    adress: {
      street: '16 de julho',
      number: '42',
      district: 'sao joao',
      city: 'porto alegre',
      state: 'rio grande do sul',
    },
    status: 'ativo',
    editing: false,
  },
  {
    name: 'astolfo cunha',
    birth: '2021-12-07',
    cpf: '180.662.160-68',
    gender: 'masculino',
    adress: {
      street: 'Tenente Coronel Fabricio Pillar',
      number: '422',
      district: 'MontSerrat',
      city: 'porto alegre',
      state: 'rio grande do sul',
    },
    status: 'ativo',
    editing: false,
  },
];
